# CS 4304 - Assignment 1

Dylan Ellsworth

201329133

September 20, 2021

### Question 1: Write that finds the number of unique fields of study

We import pandas and then open our students file, downloaded from D2L. I then decided to show some info on the dataframe, so it was easier to glance at for later questions.

In [1]:
import pandas as pd
df = pd.read_csv('students.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6221 entries, 0 to 6220
Data columns (total 9 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   REF_DATE                                                    6221 non-null   object
 1   GEO                                                         6221 non-null   object
 2   Institution type                                            6221 non-null   object
 3   Registration status                                         6221 non-null   object
 4   International Standard Classification of Education (ISCED)  6221 non-null   object
 5   Field of study                                              6221 non-null   object
 6   Gender                                                      6221 non-null   object
 7   Status of student in Canada                                 6221 non-null   object
 8   VALUE                                                       6221 non-null   float64
dtypes: float64(1), object(8)
memory usage: 437.5+ KB

In [2]:
df['Field of study'].nunique()

14

### Question 2: List all the unique degree types in the International Standard Classification of Education(ISCED) field.

An array showing the different degree types.

In [3]:
df['International Standard Classification of Education (ISCED)'].unique()

array(["Bachelor's or equivalent", "Master's or equivalent",
       'Doctoral or equivalent', 'Post-secondary non-tertiary education',
       'Short-cycle tertiary education',
       'Not applicable, International Standard Classification of Education (ISCED)',
       'Upper secondary education'], dtype=object)

### Question 3: Determine the number of entries in the data set that have institution type of University or College

We have 6221 students in either Univeristy or College, equal to the total number of rows. Therefore, every data entry is a student enrolled in either University or College.

In [4]:
df[df['Institution type'].str.contains('University')| df['Institution type'].str.contains('College')]

,REF_DATE,GEO,Institution type,Registration status,International Standard Classification of Education (ISCED),Field of study,Gender,Status of student in Canada,VALUE
0,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Male gender,Canadian students,129.0
1,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Male gender,International students,3.0
2,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Female gender,Canadian students,243.0
3,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Female gender,International students,3.0
4,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Gender unknown,Canadian students,3.0
...,...,...,...,...,...,...,...,...,...
6216,2018/2019,Territories,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Male gender,"Not reported, status of student in Canada",144.0
6217,2018/2019,Territories,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Female gender,Canadian students,810.0
6218,2018/2019,Territories,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Female gender,"Not reported, status of student in Canada",246.0
6219,2018/2019,Territories,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Gender unknown,Canadian students,216.0
6220,2018/2019,Territories,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Gender unknown,"Not reported, status of student in Canada",72.0

###  Question 4: Compute the total number of students enrolled in Newfoundland and Labrador

There are 347 students enrolled in Newfoundland and Labrador

In [5]:
df[df['GEO']== 'Newfoundland and Labrador']

,REF_DATE,GEO,Institution type,Registration status,International Standard Classification of Education (ISCED),Field of study,Gender,Status of student in Canada,VALUE
0,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Male gender,Canadian students,129.0
1,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Male gender,International students,3.0
2,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Female gender,Canadian students,243.0
3,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Female gender,International students,3.0
4,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Gender unknown,Canadian students,3.0
...,...,...,...,...,...,...,...,...,...
342,2018/2019,Newfoundland and Labrador,College,Part-time student,Short-cycle tertiary education,Unclassified,Male gender,Canadian students,0.0
343,2018/2019,Newfoundland and Labrador,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Male gender,Canadian students,720.0
344,2018/2019,Newfoundland and Labrador,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Female gender,Canadian students,402.0
345,2018/2019,Newfoundland and Labrador,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Female gender,International students,0.0
346,2018/2019,Newfoundland and Labrador,College,Part-time student,"Not applicable, International Standard Classif...",Unclassified,Gender unknown,Canadian students,3.0

### Question 5: Compute the number of female and number of male students enrolled at Memorial University of Newfoundland

We create a new dataframe for our mun students

In [6]:
df2 = df[df['Institution type'].str.contains('University') & df['GEO'].str.contains('Newfoundland and Labrador')]
df2

,REF_DATE,GEO,Institution type,Registration status,International Standard Classification of Education (ISCED),Field of study,Gender,Status of student in Canada,VALUE
0,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Male gender,Canadian students,129.0
1,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Male gender,International students,3.0
2,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Female gender,Canadian students,243.0
3,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Female gender,International students,3.0
4,2018/2019,Newfoundland and Labrador,University,Full-time student,Bachelor's or equivalent,Education [1],Gender unknown,Canadian students,3.0
...,...,...,...,...,...,...,...,...,...
234,2018/2019,Newfoundland and Labrador,University,Part-time student,Doctoral or equivalent,"Agriculture, natural resources and conservatio...",Female gender,International students,3.0
235,2018/2019,Newfoundland and Labrador,University,Part-time student,Doctoral or equivalent,Health and related fields [10],Male gender,Canadian students,18.0
236,2018/2019,Newfoundland and Labrador,University,Part-time student,Doctoral or equivalent,Health and related fields [10],Female gender,Canadian students,42.0
237,2018/2019,Newfoundland and Labrador,University,Part-time student,Doctoral or equivalent,Other [12],Male gender,Canadian students,3.0
238,2018/2019,Newfoundland and Labrador,University,Part-time student,Doctoral or equivalent,Other [12],Female gender,Canadian students,3.0

Now we just need the value counts for each male and female on our new data frame.

In [7]:
df2['Gender'].value_counts()

Male gender       113
Female gender     108
Gender unknown     18
Name: Gender, dtype: int64